// <auto-generated />
using System;
using H_Shop.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace H_Shop.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("H_Shop.Models.HShopProduct", b =>
                {
                    b.Property<long>("HShopProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("HShopProductID"), 1L, 1);

                    b.Property<decimal>("HShopProductCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HShopProductDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("HShopProductImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("HShopProductName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HShopProductID");

                    b.ToTable("HShopProducts");
                });

            modelBuilder.Entity("H_Shop.Models.HShopUser", b =>
                {
                    b.Property<int>("HShopUserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HShopUserID"), 1L, 1);

                    b.Property<string>("HShopLogin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HShopPassword")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HShopUserID");

                    b.ToTable("HShopUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
